from django import forms
from django.core.exceptions import ValidationError

class CookiePathField(forms.CharField):
    def validate(self, value): #custom Field specific validation
        super().validate(value)
        if value and not value.startswith('/cookies'):
                raise ValidationError('A valid URL path for this cookie must begin with "/cookies/"')
        

class CookieForm(forms.Form):
    random_str = forms.CharField(widget=forms.HiddenInput(), max_length=16) #generated by Javascript on the client
    max_age = forms.IntegerField(label='Maximum cookie age (seconds)', required=False, min_value=60)
    path = CookiePathField(label='Valid path', required=False, empty_value='/cookies/')
    samesite = forms.ChoiceField(choices=(('Lax', 'lax (recommended)'),('Strict', 'strict'), ('None','none')), required=False)
    httponly = forms.BooleanField(required=False)

