# Generated by Django 5.0.2 on 2024-05-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('AF', 'American Fast Food'), ('OT', 'Other')], max_length=2, null=True),
        ),
    ]
