# Generated by Django 5.0.2 on 2024-05-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_alter_sale_options_alter_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('restaurants', models.ManyToManyField(to='test2.restaurant')),
            ],
        ),
    ]
