# Generated by Django 5.0.2 on 2024-03-27 17:04

import django.db.models.deletion
import test1.models2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_familymember_father_alter_familymember_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socks', models.PositiveIntegerField(validators=[test1.models2.check_even])),
                ('clothes', models.PositiveIntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closet', to='test1.familymember', validators=[test1.models2.check_person])),
            ],
        ),
    ]
