# Generated by Django 5.0.2 on 2024-03-27 19:49

import test1.models2
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_closet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='socks',
            field=test1.models2.EvenIntegerField(),
        ),
    ]
