# Generated by Django 5.0.2 on 2024-03-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_alter_closet_socks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closet',
            old_name='owner',
            new_name='belongs_to',
        ),
    ]
